### ISSUE TITLE
Authorized Chats

### ISSUE THREAD

**Issue by noob-gmr** [SVR666/LoaderX-Bot#2]
![photo_2020-07-29_11-06-35](https://user-images.githubusercontent.com/64120834/88761042-f4721d00-d18b-11ea-88b0-73e46c6b4a98.jpg)

After the recent repo update this error shows when pushing with authorized_chats.txt. Without this no error shows.
Wouth chats there is no problem  I have committed all changes in repo. Any solution?

**Comment by SVR666** [comment]
https://t.me/joinchat/NG6qaRTFYEdcKWpiMlZ4eg
join this grp for help

**Comment by SVR666** [comment]
u modified code ?

**Comment by noob-gmr** [comment]
> u modified code ?

no nothing

**Comment by SVR666** [comment]
> no nothing

https://t.me/joinchat/NG6qaRTFYEdcKWpiMlZ4eg
join this grp

**Comment by SVR666** [comment]
if u r using this https://github.com/lzzy12/python-aria-mirror-bot Repo then idk..
and i think u r using that
